### ISSUE TITLE
[bug] Cannot run the application

### ISSUE THREAD

**Issue by GibStorm** [techygrrrl/multilang-twitch-tts#5]
As stated, I cannot even run the app. I am on Windows 11, if that helps.

**Comment by techygrrrl** [comment]
Do you get an error? Did you allow running of the app for unknown developers?

Install instructions state:

> I am not registered as a developer on Microsoft's platform so if you have trouble installing this app, you may need to change your permissions and either allow installing apps from unknown publishers, or specifically unblock this app.

Without details of your error I'm unable to help.

**Comment by GibStorm** [comment]
No error, no nothing. The app just never starts. I've selected "run anyway" The first time, since the app isn’t signed. Even rebooted the computer to see if that helped. It did not.

**Comment by Nikos4Life** [comment]
Same problem, it just won't open. I can not provide any info due to the program not even starting. Installation goes as expected though

**Comment by techygrrrl** [comment]
I am able to reproduce this bug you both experience @Nikos4Life and @GibStorm after a Windows update. It appears that after a Windows update, Windows conveniently removes my installed voices in other languages. Unfortunately, I am not checking for the presence of these voices before trying to use them, so there is a bug that lies there.

Can you try installing both a French and a Spanish voice? I think that should fix it until I am able to make a fix that more intelligently chooses voices.

You can do this in the Speech Settings.

![image](https://user-images.githubusercontent.com/88961088/204108239-3580a432-390d-406b-a86a-ab5d01a448be.png)

For example, I've installed the following voices and it's now working.

![image](https://user-images.githubusercontent.com/88961088/204108406-8704c610-e0d3-40e7-82e9-0fe5eeaeb480.png)

One of the things I noticed when installing voices is that it takes  a long time for a voice to be installed and there's no indication of whether the voice has been installed or not, so I needed to keep quitting the settings and reopening to see if it shows in the above list. 

After ensuring the voices show up in the list in the Speech settings, try re-opening the TTS app. I needed to reopen the TTS app a few times as it still failed even after the voices were installed. It appears that it takes some time  for Windows to propagate the voices to be available for apps. 

Thanks again for reporting. Let me know if you try this workaround and if it helps.

**Comment by GoddessRandi** [comment]
I'm still having an issue with launching the application on windows 10 even after installing the languages. I'm getting a .NET Runtime and Application error in event logs when attempting to launch. Let me know if you need any additional info to assist.

.NET

Application: TwitchTTSMultilang.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Linq.Enumerable.First[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>)
   at TwitchTTSMultilang.MainWindow.initVoices()
   at TwitchTTSMultilang.MainWindow..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.LoadComponent(System.Uri, Boolean)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at TwitchTTSMultilang.App.Main()

Application

Faulting application name: TwitchTTSMultilang.exe, version: 1.0.0.0, time stamp: 0x9775386a
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2604, time stamp: 0xce23fdc3
Exception code: 0xe0434352
Fault offset: 0x0012e4b2
Faulting process id: 0x1378
Faulting application start time: 0x01d9424482a3197f
Faulting application path: C:\Users\*****\AppData\Local\Apps\2.0\950MT1EO.5G3\M6YPC12Y.KNM\twit..tion_3cdfd4990ebc1089_0001.0000_2eb1226fd46c1e51\TwitchTTSMultilang.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 578e80cf-fd29-4b15-853d-c804bf11ec44
Faulting package full name: 
Faulting package-relative application ID:

**Comment by techygrrrl** [comment]
Thanks for reporting this @GoddessRandi ... I'll have to look into this.

**Comment by techygrrrl** [comment]
@GibStorm @GoddessRandi @Nikos4Life can you try this build: https://github.com/techygrrrl/multilang-twitch-tts/releases/tag/1.0.0.21

I was troubleshooting the build just now, it's bigger so I think it's bundled with .NET. It should work but let me know.

**Comment by techygrrrl** [comment]
@GibStorm @GoddessRandi @Nikos4Life have you tried this build to confirm if this is still an issue for you: https://github.com/techygrrrl/multilang-twitch-tts/releases/tag/1.0.0.21

**Comment by GoddessRandi** [comment]
> @GibStorm @GoddessRandi @Nikos4Life have you tried this build to confirm if this is still an issue for you: https://github.com/techygrrrl/multilang-twitch-tts/releases/tag/1.0.0.21

Yes! This build worked for me. Thank you!

**Comment by techygrrrl** [comment]
Thanks for testing @GoddessRandi I'm glad to hear! 🎉
